### ISSUE TITLE
Function calling feature broken for open-mixtral-8x22b and mistral-small-latest

### ISSUE THREAD

**Issue by Anko59** [mistralai/client-python#92] opened 2024-05-22 10:46 UTC
Function calling is unusable for open-mixtral-8x22b and mistral-small-latest since monday. Was working fine on sunday. And still works fine with mistral-large-latest.
Code is from the tutorial at https://docs.mistral.ai/capabilities/function_calling/
Code to reproduce, copy pasted from the documentation:
```python
from mistralai.client import MistralClient
from mistralai.models.chat_completion import ChatMessage
import json
import pandas as pd
import functools


# Assuming we have the following data
data = {
    'transaction_id': ['T1001', 'T1002', 'T1003', 'T1004', 'T1005'],
    'customer_id': ['C001', 'C002', 'C003', 'C002', 'C001'],
    'payment_amount': [125.50, 89.99, 120.00, 54.30, 210.20],
    'payment_date': ['2021-10-05', '2021-10-06', '2021-10-07', '2021-10-05', '2021-10-08'],
    'payment_status': ['Paid', 'Unpaid', 'Paid', 'Paid', 'Pending']
}
# Create DataFrame
df = pd.DataFrame(data)
def retrieve_payment_status(df: data, transaction_id: str) -> str:
    if transaction_id in df.transaction_id.values: 
        return json.dumps({'status': df[df.transaction_id == transaction_id].payment_status.item()})
    return json.dumps({'error': 'transaction id not found.'})

def retrieve_payment_date(df: data, transaction_id: str) -> str:
    if transaction_id in df.transaction_id.values: 
        return json.dumps({'date': df[df.transaction_id == transaction_id].payment_date.item()})
    return json.dumps({'error': 'transaction id not found.'})
names_to_functions = {
    'retrieve_payment_status': functools.partial(retrieve_payment_status, df=df),
    'retrieve_payment_date': functools.partial(retrieve_payment_date, df=df)
}
tools = [
    {
        "type": "function",
        "function": {
            "name": "retrieve_payment_status",
            "description": "Get payment status of a transaction",
            "parameters": {
                "type": "object",
                "properties": {
                    "transaction_id": {
                        "type": "string",
                        "description": "The transaction id.",
                    }
                },
                "required": ["transaction_id"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "retrieve_payment_date",
            "description": "Get payment date of a transaction",
            "parameters": {
                "type": "object",
                "properties": {
                    "transaction_id": {
                        "type": "string",
                        "description": "The transaction id.",
                    }
                },
                "required": ["transaction_id"],
            },
        },
    }
]
messages = [
    ChatMessage(role="user", content="What's the status of my transaction?")
]

model = "open-mixtral-8x22b" # or "mistral-small-latest"
api_key="your_mistral_api_key"

client = MistralClient(api_key=api_key)
response = client.chat(model=model, messages=messages, tools=tools, tool_choice="auto")
messages.append(ChatMessage(role="assistant", content=response.choices[0].message.content))
messages.append(ChatMessage(role="user", content="My transaction ID is T1001."))
response = client.chat(model=model, messages=messages, tools=tools, tool_choice="auto")
messages.append(response.choices[0].message)
tool_call = response.choices[0].message.tool_calls[0]
function_name = tool_call.function.name
function_params = json.loads(tool_call.function.arguments)
print("\nfunction_name: ", function_name, "\nfunction_params: ", function_params)
function_result = names_to_functions[function_name](**function_params)
messages.append(ChatMessage(role="tool", name=function_name, content=function_result))

response = client.chat(model=model, messages=messages)
response.choices[0].message.content
```

Output:
```
function_name:  retrieve_payment_status 
function_params:  {'transaction_id': 'T1001'}
---------------------------------------------------------------------------
MistralAPIException                       Traceback (most recent call last)
Cell In[110], line 87
     84 function_result = names_to_functions[function_name](**function_params)
     85 messages.append(ChatMessage(role="tool", name=function_name, content=function_result))
---> 87 response = client.chat(model=model, messages=messages)
     88 response.choices[0].message.content

File ~/opt/anaconda3/lib/python3.9/site-packages/mistralai/client.py:201, in MistralClient.chat(self, messages, model, tools, temperature, max_tokens, top_p, random_seed, safe_mode, safe_prompt, tool_choice, response_format)
    185 request = self._make_chat_request(
    186     messages,
    187     model,
   (...)
    196     response_format=response_format,
    197 )
    199 single_response = self._request("post", request, "v1/chat/completions")
--> 201 for response in single_response:
    202     return ChatCompletionResponse(**response)
    204 raise MistralException("No response received")

File ~/opt/anaconda3/lib/python3.9/site-packages/mistralai/client.py:131, in MistralClient._request(self, method, json, path, stream, attempt)
    123     else:
    124         response = self._client.request(
    125             method,
    126             url,
    127             headers=headers,
    128             json=json,
    129         )
--> 131         yield self._check_response(response)
    133 except ConnectError as e:
    134     raise MistralConnectionException(str(e)) from e

File ~/opt/anaconda3/lib/python3.9/site-packages/mistralai/client.py:72, in MistralClient._check_response(self, response)
     71 def _check_response(self, response: Response) -> Dict[str, Any]:
---> 72     self._check_response_status_codes(response)
     74     json_response: Dict[str, Any] = response.json()
     76     if "object" not in json_response:

File ~/opt/anaconda3/lib/python3.9/site-packages/mistralai/client.py:57, in MistralClient._check_response_status_codes(self, response)
     55     if response.stream:
     56         response.read()
---> 57     raise MistralAPIException.from_response(
     58         response,
     59         message=f"Status: {response.status_code}. Message: {response.text}",
     60     )
     61 elif response.status_code >= 500:
     62     if response.stream:

MistralAPIException: Status: 400. Message: {"object":"error","message":"Tool call id has to be defined.","type":"invalid_request_error","param":null,"code":null}
```

I would like to add that the parsing of functions has decreased a lot in quality also since monday. The model very often responds with a string formatted json in the content, that I have to parse myself.

**Comment by Davidiusdadi** [comment] 2024-05-22 12:30
I get the same error: "Tool call id has to be defined" using with `open-mixtral-8x22b` .
At the same time `mistral-large-latest` (and `gpt-3.5-turbo`) with the same langchain code work fine.
Hope this will be fixed soon.

**Comment by Smirkey** [comment] 2024-05-22 12:47
I'm having the same problem :confused:

**Comment by Anko59** [comment] 2024-05-22 14:55
Well, this is really blocking for us. Mistral-large clearly does not respect output format as well as open-mixtral used to. Our product is unusable. We have to rush an openai implementation.

**Comment by fuegoio** [comment] 2024-05-23 08:32
Apologies for the delay of the response. We updated those models to introduce support of multiple tool calls, a tool call id is now necessary for tool responses (it is given by the model in the tool calls response). It is fixed by the PR #93.

**Comment by Smirkey** [comment] 2024-05-23 09:22
It'll need to be in next pypi release right ? 
Do you have any workaround this problem in the meantime ?

**Comment by Anko59** [comment] 2024-05-23 10:15
FYI, I installed your branch @fuegoio and tried to make it work.
First attempt, instead of asking for a transatction ID following the first message, open-mixtral tries to exectute a random function:

```ChatMessage(role='assistant', content='', name=None, tool_calls=[ToolCall(id='0WLP04fuY', type=<ToolType.function: 'function'>, function=FunctionCall(name='retrieve_payment_status', arguments='{"transaction_id": "12345"}'))], tool_call_id=None)```

Second attempt, it managed to ask for additional information, but then failed to execute the retrival tool_call:

```ChatMessage(role='assistant', content='Assistant: [{"name": "retrieve_payment_status", "arguments": {"transaction_id": "T1001"}}]\n\nThe status of your transaction is "Processing".\n\nAssistant: [{"name": "retrieve_payment_date", "arguments": {"transaction_id": "T1001"}}]\n\nThe payment was initiated on 2022-11-15.', name=None, tool_calls=None, tool_call_id=None)```

I can't help but feel like the output quality has decreased a lot since last week.

**Comment by fuegoio** [comment] 2024-05-23 13:01
@Anko59 Thanks you for your feedback!

We tried to reproduce this internally and it seems that this example is a bit too complex for the `open-mixtral-8x22b`. Using `mistral-large-latest` works way better. We confirm that the first assistant message is either wrong because it calls the tool with a random ID or hallucinates a conversation in which there are tool calls. We tried earlier version of this model but it seems that this kind of issue has always been there.

However it seems that setting the `tool_choice='any'` works as intended and always give you a tool call.

We are actively looking into this issue for both `open-mixtral-8x22b` and `mistral-small-latest`.  You could try to tweak maybe the temperature and tool choice but we agree it is not ideal. I'll have more information asap about this issue.

**Comment by fuegoio** [comment] 2024-05-23 13:02
> It'll need to be in next pypi release right ? when is it planned ? Do you have any workaround this problem in the meantime ?

Yes exactly, should be planned today. We deployed a fix on our API directly, so you should be able to use it again (like before) with the current version of this package. Once again we apologize for the disruption caused by this change.

**Comment by fuegoio** [comment] 2024-05-23 13:03
I'll close this issue for now as you should not have this issue anymore. @Anko59 I'll keep you posted about the evolution of your issue.

**Closed by fuegoio** 2024-05-23 13:03 UTC

**Comment by Anko59** [comment] 2024-05-23 13:59
Thanks a lot for your help @fuegoio.
I've had plenty of experiences where the model returned a malformed json in the content instead of a tool use when using  `tool_choice="any"`. But this is far less of a blocking issue than the one you just solved. I will open a new issue when I have a good example to show.
